FROM quay.io/jeani/base_ubuntu_cuda_ucx:latest

# Authors Jean Iaquinta
# Contact jeani@uio.no
# Version v1.0.0
#
# This is a definition file for a container based on Ubuntu22.04 with MPIch4.2.1 and support for UCX1.17.0 and Cuda12.1.0
#
# Update system and install basic packages

# MPICH version 4.2.1
RUN wget -q -nc --no-check-certificate -P /var/tmp https://www.mpich.org/static/downloads/4.2.1/mpich-4.2.1.tar.gz && \
    tar -x -f /var/tmp/mpich-4.2.1.tar.gz -C /var/tmp -z && \
     cd /var/tmp/mpich-4.2.1 && CC=gcc CXX=g++ F77=gfortran FC=gfortran ./configure --prefix=/usr/local/mpich --enable-fast=O3 --enable-romio --with-device=ch4:ucx --with-hwloc=embedded --enable-nemesis-shm-collectives --with-cuda=/etc/alternatives/cuda CFLAGS="-I/usr/local/cuda-12.1/targets/x86_64-linux/include" LDFLAGS="-L/usr/local/cuda-12.1/compat" && \
    make -j$(nproc) &&  make -j$(nproc) install && \
    echo "/usr/local/mpich/lib" >> /etc/ld.so.conf.d/espresso.conf && ldconfig && \
    rm -rf /var/tmp/mpich-4.2.1 /var/tmp/mpich-4.2.1.tar.gz
ENV PATH=/usr/local/mpich/bin:$PATH \
    MPICH_HOME=/usr/local/mpich 

# --------------------------------------------------------------------------------------------------------------------
